# This workflow will publish the release artifacts.

name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  release:
    types: [published]
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
    - name: Upload JARs to release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "jdbc/target/*.jar"