# This workflow will publish the release artifacts.

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1
    - name: Package up release files
      run: |
        sudo apt-get install zip
        mkdir BabelfishCompass
        cp BabelfishCompass.bat BabelfishCompass/
        cp BabelfishFeatures.cfg BabelfishCompass/
        cp THIRD-PARTY-LICENSES.txt BabelfishCompass/
        cp target/compass-1.0.jar BabelfishCompass/
        cp LICENSE BabelfishCompass/
        cp NOTICE BabelfishCompass/
        zip -r BabelfishCompass.zip BabelfishCompass
    - name: Upload JARs to release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "BabelfishCompass.zip"