# This workflow will publish the release artifacts.

name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  release:
    types: [published]
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload JARs to release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        automatic_release_tag: "latest"
        title: "Example Release ${GITHUB_REF#refs/tags/}"
        files: |
          jdbc/target/*.jar
